steps:
# checkout the repo
    - uses: actions/checkout@master

    # login using azure credentials
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.MySecondAppAJSN_8919 }}

    - uses: actions/setup-node@v1
      with:
        node-version: 16.x

    # install dependencies, build, and test
    - name: npm install, build, and test
      working-directory: .
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - uses: azure/appservice-settings@v1
      with:
        app-name: MySecondAppAJSN
        general-settings-json: '{"linuxFxVersion": "NODE|16-lts"}' #'General configuration settings as Key Value pairs'

    # deploy web app
    - uses: azure/webapps-deploy@v1
      with:
        app-name: MySecondAppAJSN
        package: .

    # Azure logout
    - name: logout
      run: |
        az logout