# Plain Node.js on Linux Web App
# Build a plain Node.js project and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:

on:
  push:
    branches:
      - master

name: Build and deploy Plain Node.js on Linux Web App

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    -template: steps.yml